// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LightNap.Core.Email.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Web;
    using LightNap.Core.Data.Entities;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\edkai\source\repos\SharpLogic\LightNap\src\LightNap.Core\Email\Templates\ChangeEmailTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ChangeEmailTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 9 "C:\Users\edkai\source\repos\SharpLogic\LightNap\src\LightNap.Core\Email\Templates\ChangeEmailTemplate.tt"
 base.TransformText(); 
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 11 "C:\Users\edkai\source\repos\SharpLogic\LightNap\src\LightNap.Core\Email\Templates\ChangeEmailTemplate.tt"
 
	public string Token { get; set; }
	public string NewEmail { get; set; }
	public string LinkUrl => $"{this.SiteUrlRoot}profile/confirm-email-change/{HttpUtility.UrlEncode(this.NewEmail)}/{HttpUtility.UrlEncode(this.Token)}";
	protected override void RenderBody() 
	{

        
        #line default
        #line hidden
        
        #line 17 "C:\Users\edkai\source\repos\SharpLogic\LightNap\src\LightNap.Core\Email\Templates\ChangeEmailTemplate.tt"
this.Write("<p>Please confirm your email change <a href=\"");

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\edkai\source\repos\SharpLogic\LightNap\src\LightNap.Core\Email\Templates\ChangeEmailTemplate.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(LinkUrl));

        
        #line default
        #line hidden
        
        #line 18 "C:\Users\edkai\source\repos\SharpLogic\LightNap\src\LightNap.Core\Email\Templates\ChangeEmailTemplate.tt"
this.Write("\">here</a>.</p>\r\n");

        
        #line default
        #line hidden
        
        #line 19 "C:\Users\edkai\source\repos\SharpLogic\LightNap\src\LightNap.Core\Email\Templates\ChangeEmailTemplate.tt"

	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
